/**
 * 模型中心 — 静态模拟数据（开发测试用）
 * @author Antigravity/Gemini
 */
import type { ModelCenterInitialData } from './api/model-center-api';

export const MOCK_MODEL_CENTER_DATA: ModelCenterInitialData = {
  providers: [
    {
      id: 'openai-compat',
      code: 'openai-compat',
      name: 'OpenAI 兼容网关',
      type: 'OPENAI_COMPATIBLE',
      baseUrl: 'https://api.openai.com/v1',
      apiKey: 'sk-***',
      status: '启用',
    },
    {
      id: 'qwen-bailian',
      code: 'qwen-bailian',
      name: '阿里云百炼（通义千问）',
      type: 'QWEN',
      baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
      apiKey: 'sk-***',
      status: '启用',
    },
    {
      id: 'deepseek-official',
      code: 'deepseek-official',
      name: 'DeepSeek 官方',
      type: 'DEEPSEEK',
      baseUrl: 'https://api.deepseek.com',
      apiKey: 'sk-***',
      status: '停用',
    },
  ],
  models: [
    {
      id: '1',
      name: 'GPT-4.1 Mini',
      provider: 'openai-compat',
      providerName: 'OpenAI 兼容网关',
      providerType: 'OPENAI_COMPATIBLE',
      modelId: 'gpt-4.1-mini',
      modelType: 'LLM',
      protocol: 'OPENAI_CHAT_COMPLETIONS',
      parameters: { stream: true, jsonMode: true, toolCalling: true, maxOutputTokens: 4096 },
      capabilities: { stream: true, jsonMode: true, toolCalling: true },
      limits: { contextWindow: 128000, maxOutputTokens: 4096 },
      status: '启用',
    },
    {
      id: '2',
      name: 'Text Embedding 3 Large',
      provider: 'openai-compat',
      providerName: 'OpenAI 兼容网关',
      providerType: 'OPENAI_COMPATIBLE',
      modelId: 'text-embedding-3-large',
      modelType: 'EMBEDDING',
      protocol: 'OPENAI_EMBEDDINGS',
      parameters: { dimensions: 3072 },
      capabilities: { embedding: true },
      limits: { maxInputTokens: 8192, embeddingDimensions: 3072 },
      status: '启用',
    },
    {
      id: '3',
      name: 'Qwen Plus',
      provider: 'qwen-bailian',
      providerName: '阿里云百炼（通义千问）',
      providerType: 'QWEN',
      modelId: 'qwen-plus',
      modelType: 'LLM',
      protocol: 'DASHSCOPE_COMPATIBLE_CHAT',
      parameters: { stream: true, jsonMode: true, maxOutputTokens: 8192 },
      capabilities: { stream: true, jsonMode: true },
      limits: { contextWindow: 128000, maxOutputTokens: 8192 },
      status: '启用',
    },
    {
      id: '4',
      name: 'DeepSeek Chat',
      provider: 'deepseek-official',
      providerName: 'DeepSeek 官方',
      providerType: 'DEEPSEEK',
      modelId: 'deepseek-chat',
      modelType: 'LLM',
      protocol: 'DEEPSEEK_CHAT_COMPLETIONS',
      parameters: { stream: true, thinkingEnabled: true },
      capabilities: { stream: true, reasoning: true },
      limits: { contextWindow: 64000, maxOutputTokens: 4096 },
      status: '停用',
    },
  ],
};
